SELECT TOP (1000) [ID]
      ,[UserID]
      ,[RoomName]
      ,[RoomID]
      ,[CheckIn]
      ,[CheckOut]
      ,[Guests]
      ,[TotalPrice]
      ,[Email]
      ,[CCCD]
      ,[DOB]
      ,[Hometown]
      ,[NgayDat]
      ,[Trạng thái]
      ,[RoomCode]
  FROM [Khachsannhom11].[dbo].[DatPhong]
